services:
  portainer:
    hostname: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../portainer:/data
    restart: always
    networks:
      - systems

networks:
  systems:
    external:
      name: systems