name: "Build & push to Dockerhub"

on:
  push:
    branches:
      - main
      - v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Copy data
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD  }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: |
            "paschendale/skyforest-geoserver-uploader:latest"