name: "Build & push to Dockerhub"

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Copy data
        uses: actions/checkout@v3

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push uploader image
        if: contains(steps.files.outputs.all, 'uploader')
        uses: docker/build-push-action@v5
        with:
          context: ./uploader
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./uploader/Dockerfile
          push: true
          tags: skyforestab/geoserver-uploader:latest

      - name: Build and push Geoserver image
        if: contains(steps.files.outputs.all, 'Dockerfile.geoserver')
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile.geoserver
          push: true
          tags: skyforestab/geoserver:latest

      - name: Build and push Colossus image
        if: contains(steps.files.outputs.all, 'colossus')
        uses: docker/build-push-action@v5
        with:
          context: ./colossus
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./colossus/Dockerfile
          push: true
          tags: skyforestab/colossus:latest

      - name: Build and push Shipyard image
        if: contains(steps.files.outputs.all, 'shipyard')
        uses: docker/build-push-action@v5
        with:
          context: ./shipyard
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./shipyard/Dockerfile
          push: true
          tags: skyforestab/shipyard:latest
